Issue 15
kripsy/gophermart pull request #19
Opened 2023-07-07 04:44 UTC by KorsakovPV

Добавил миграции для gophermart

2023-07-08 17:10 UTC, kripsy requested changes

2023-07-10 02:12 UTC, KorsakovPV commented on db/migrations/gophermart/20230706165956_init.up.sql
> +    user_id      text                     not null,
заменил на bigint

2023-07-10 02:43 UTC, KorsakovPV commented on db/migrations/gophermart/20230706165956_init.up.sql
> +    status       text,
Я подумал после зозвона про статус. Сначала мне идея показалась классной в духе реляционных баз данных. Но потом создавать базу только для значения статусов мне показалось избуточным. Темболее что в постгрес есть свои ENUM

https://www.postgresql.org/docs/current/datatype-enum.html

Сейчас я думаю создать енум не на уровне базы, а на уровне кода и валидировать там.

2023-07-10 02:44 UTC, KorsakovPV commented on db/migrations/gophermart/20230706165956_init.up.sql
> +    status       text,
Артема спрошу.

2023-07-10 02:45 UTC, KorsakovPV commented on db/migrations/gophermart/20230706165956_init.up.sql
> +    user_id      text                     not null,
поправил на bigint

2023-07-10 08:39 UTC, kripsy commented on db/migrations/gophermart/20230706165956_init.up.sql
> +    user_id      text                     not null,
нужно поле username varchar(255)

2023-07-12 15:34 UTC, kripsy commented on db/migrations/gophermart/20230706165956_init.up.sql
> +    user_id      text                     not null,
плииииз, пусть это будет поле username, молю)))

2023-07-12 15:42 UTC, merged